pull_request_rules:
  - name: merge jika semua require sudah terpenuhi
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
    actions:
      comment:
        message: terima kasih atas kontribusinya @{{ author }}!
      label:
        add:
          - sudah di review!
      merge:
        method: merge
