pull_request_rules:
  - name: merge jika semua require sudah terpenuhi
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      comment:
        message: terima kasih atas kontribusinya @{{ author }}!
      label:
        add:
          - sudah di review!
      
      merge:
        method: squash

  - name: label python
    conditions:
    - files~=\.py$
    actions:
    label:
      - file python
